# Generated by Django 4.2.9 on 2024-07-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='addSettings',
            field=models.ManyToManyField(blank=True, null=True, to='home.additionalsettings'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='admin',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'Admin'}, related_name='admin_computers', to='home.username'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='home.customer'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='diskPlace',
            field=models.ManyToManyField(blank=True, null=True, to='home.diskplace'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer', to='home.employee'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hardDisk',
            field=models.ManyToManyField(to='home.harddisk'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='lanCard',
            field=models.ManyToManyField(to='home.lancard'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='monitor',
            field=models.ManyToManyField(blank=True, null=True, to='home.monitor'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.ManyToManyField(to='home.processor'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.ManyToManyField(to='home.ram'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='typeDB',
            field=models.ManyToManyField(to='home.typedb'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='user',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'User'}, related_name='user_computers', to='home.username'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='videoCard',
            field=models.ManyToManyField(to='home.videocard'),
        ),
        migrations.AlterField(
            model_name='location',
            name='computer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.computer'),
        ),
        migrations.AlterField(
            model_name='order_computer',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.computer'),
        ),
        migrations.AlterField(
            model_name='order_computer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
    ]
