# Generated by Django 4.2.9 on 2024-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_computer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='custom_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('Computer1', 'Fujitsu ESPRIMO P5011'), ('Computer2', 'Fujitsu ESPRIMO P558/E85+'), ('Computer3', 'Fujitsu ESPRIMO P557')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_computer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
