# Generated by Django 4.2.9 on 2024-07-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_computer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_computer',
            name='customer',
        ),
    ]
