# Generated by Django 4.2.9 on 2024-07-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_order_computer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computers', to='home.customer'),
        ),
    ]
