# Generated by Django 4.2.9 on 2024-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_computer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='login',
            field=models.CharField(default='Administrator', max_length=20),
        ),
        migrations.AlterField(
            model_name='username',
            name='password',
            field=models.CharField(default='icom', max_length=20),
        ),
        migrations.AlterField(
            model_name='username',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=5),
        ),
    ]
