# Generated by Django 4.2.9 on 2024-07-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_username_login_alter_username_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='name',
        ),
        migrations.AddField(
            model_name='computer',
            name='location',
            field=models.ManyToManyField(related_name='location_computers', to='home.location'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='addSettings',
            field=models.ManyToManyField(blank=True, to='home.additionalsettings'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='diskPlace',
            field=models.ManyToManyField(blank=True, to='home.diskplace'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='monitor',
            field=models.ManyToManyField(blank=True, to='home.monitor'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='user',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'User'}, related_name='user_computers', to='home.username'),
        ),
        migrations.AlterField(
            model_name='location',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='home.computer'),
        ),
    ]
