# Generated by Django 4.2.9 on 2024-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_place_location_name_computer_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='computer',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
