# Generated by Django 4.2.9 on 2024-07-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_computer_location_delete_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='home.computer')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='location',
            field=models.ManyToManyField(related_name='location_computers', to='home.location'),
        ),
    ]
