# Generated by Django 4.2.9 on 2024-07-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_computer_location_location_computer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='location',
        ),
    ]
