# Generated by Django 4.2.9 on 2024-07-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_computer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancard',
            name='series',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
    ]
