# Generated by Django 4.2.9 on 2024-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_lancard_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('licenseNumber', models.CharField(max_length=60)),
                ('licenseKeys', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='windows',
            field=models.ManyToManyField(to='home.windows'),
        ),
    ]
