# Generated by Django 4.2.9 on 2024-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_windows_computer_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(blank=True, choices=[('Fujitsu ESPRIMO P5011', 'Fujitsu ESPRIMO P5011'), ('Fujitsu ESPRIMO G9013 ESTAR', 'Fujitsu ESPRIMO G9013 ESTAR'), ('Fujitsu ESPRIMO P558/E85+', 'Fujitsu ESPRIMO P558/E85+'), ('Fujitsu ESPRIMO P557', 'Fujitsu ESPRIMO P557')], max_length=30, null=True),
        ),
    ]
