# Generated by Django 4.2.9 on 2024-07-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_computer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='admin',
        ),
        migrations.AlterField(
            model_name='computer',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_computers', to='home.username'),
        ),
    ]
