# Generated by Django 4.2.9 on 2024-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_computer_admin_alter_computer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='login',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='username',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='username',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=5),
        ),
    ]
