# Generated by Django 4.2.9 on 2024-07-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_computer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='windows',
        ),
        migrations.AddField(
            model_name='windows',
            name='computer',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='home.computer'),
            preserve_default=False,
        ),
    ]
