# Generated by Django 4.2.9 on 2024-07-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_computer_windows_windows_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windows',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windowses', to='home.computer'),
        ),
    ]
