# Generated by Django 4.2.9 on 2024-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_windows_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='date',
            field=models.DateField(),
        ),
    ]
