# Generated by Django 4.2.9 on 2024-07-29 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_computer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='computers', to='home.customer'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer', to='home.employee'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hardDisk',
            field=models.ManyToManyField(blank=True, to='home.harddisk'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='lanCard',
            field=models.ManyToManyField(blank=True, to='home.lancard'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.ManyToManyField(blank=True, to='home.processor'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.ManyToManyField(blank=True, to='home.ram'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Progress', 'In Progress'), ('Ready', 'Ready'), ('Confirm', 'Confirm')], default='Progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='typeDB',
            field=models.ManyToManyField(blank=True, to='home.typedb'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='videoCard',
            field=models.ManyToManyField(blank=True, to='home.videocard'),
        ),
    ]
