# Generated by Django 4.2.9 on 2024-07-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_computer_customer_alter_computer_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
