# Generated by Django 4.2.9 on 2024-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_computer_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='gigabytes',
            field=models.PositiveSmallIntegerField(choices=[('16', '16'), ('32', '32'), ('64', '64'), ('128', '128')]),
        ),
    ]
