# Generated by Django 4.2.9 on 2024-07-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_computer_date_alter_ram_gigabytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4')], max_length=10),
        ),
    ]
