# Generated by Django 4.2.9 on 2024-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_ram_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harddisk',
            name='gigabytes',
            field=models.PositiveSmallIntegerField(choices=[('128', '128'), ('256', '256'), ('512', '512'), ('1024', '1024')]),
        ),
        migrations.AlterField(
            model_name='harddisk',
            name='type',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=10),
        ),
    ]
